export const SET_VIEW = 'SET_VIEW';
export const SET_TAB = 'SET_TAB';
export const SET_BOT_CONTEXT = 'SET_BOT_CONTEXT';
export const SET_QUIZ_DIFFICULTY = 'SET_QUIZ_DIFFICULTY';
export const SET_CURRENT_QUIZ = 'SET_CURRENT_QUIZ';
export const SET_CURRENT_QUESTION_INDEX = 'SET_CURRENT_QUESTION_INDEX';
export const SET_USER_ANSWERS = 'SET_USER_ANSWERS';
