export const CREATE_CITADEL = 'CREATE_CITADEL';
export const SET_CITADEL = 'SET_CITADEL';
export const SET_HEADQUARTER = 'SET_HEADQUARTER';
export const SET_BUILDINGS = 'SET_BUILDINGS';
export const SET_BUILDINGS_DATA = 'SET_BUILDINGS_DATA';
export const SET_CITADEL_BUILDING_LEVEL = 'SET_CITADEL_BUILDING_LEVEL';
export const UPDATE_RESSOURCES = 'UPDATE_RESSOURCES';
export const SET_RESSOURCES = 'SET_RESSOURCES';
export const SET_LEVEL_UP = 'SET_LEVEL_UP';
export const SET_END_UPGRADE_TIME = 'SET_END_UPGRADE_TIME';

