export const SET_VIEW_TYPE = 'SET_VIEW_TYPE';
export const SET_BUILDING_VIEW = 'SET_BUILDING_VIEW';
export const SET_CURRENT_BUILDING_DATA = 'SET_CURRENT_BUILDING_DATA';
export const SET_BUILDING_LEVEL = 'SET_BUILDING_LEVEL';
